version: '2'
services:
  secureweb:
    # For local access, run this command in the terminal
    # echo "127.0.1.1 secureweb" >> /etc/hosts
    image: aheimsbakk/https-proxy:4
    ports:
    - 80:80
    - 443:443
    links:
    - web:http
    restart: always
    volumes:
    - ./tests/fixtures/certs/secureweb:/etc/ssl/private
    environment:
    - SERVER_NAME=secureweb
    - SERVER_ADMIN=webmaster@mydomain.com
    - PORT_REDIRECT=8080
    - SSL_CERT_FILE=/etc/ssl/private/MyKeystore.crt
    - SSL_PRIVKEY_FILE=/etc/ssl/private/MyKeystore.key
    - SSL_CHAIN_FILE=/etc/ssl/private/MyKeystore.p12
  web:
    image: fpfis/httpd-php-dev:7.1
    working_dir: /var/www/html
    ports:
    - 8080:8080
    volumes:
    - .:/var/www/html # Non Mac users.
    # - ~/.cache/composer:/root/.composer/cache # use a local cache.
    # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    environment:
      # For Xdebug setup:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      # Run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
  mysql:
    image: percona/percona-server:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
    - 3306:3306
  # Spawn a Selenium server which also includes a VNC server on localhost:5900 (the password is "secret")
  selenium:
    image: selenium/standalone-chrome-debug:3.11
    environment:
    - DISPLAY=:99
    - SE_OPTS=-debug
    ports:
    - 5900:5900
    expose:
    - 4444
  authentication:
    # For local access, run this command in the terminal
    # echo "127.0.1.1 authentication" >> /etc/hosts
    image: registry.fpfis.tech.ec.europa.eu/ecas-mock-server:4.6.0
    volumes:
    - ./tests/fixtures/ecas-mockup-config:/data/ecas-mock-server-shared
    ports:
    - 7001:7001
    - 7002:7002
    - 7003:7003

#### Mac users: uncomment the "volumes" key to enable the NFS file sharing. You can find more information about Docker for Mac here: https://github.com/openeuropa/openeuropa/blob/master/docs/starting/tooling.md#using-docker-on-macos
#volumes:
#  nfsmount:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#      device: ":${PWD}/"
#### End Mac users.
